# 基础 USB 功能（必须）
CONFIG_ZMK_USB=y

# 蓝牙功能（必须）
CONFIG_ZMK_BLE=y

# 自动休眠省电
CONFIG_ZMK_SLEEP=y

# 开启串口（ZMK Studio 必须）
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_INTERRUPT_DRIVEN=y

# 开启 ZMK Studio 支持
CONFIG_ZMK_STUDIO=y

# 基础 GPIO
CONFIG_GPIO=y
